services:
  msp-beacon:
    image: ghcr.io/anthonyjohnsonga/msp-beacon:latest
    container_name: msp-beacon
    ports:
      - "3000:3000"
    volumes:
      - msp-beacon-data:/data
    restart: unless-stopped

volumes:
  msp-beacon-data:
