services:
  msp-beacon:
    image: ghcr.io/anthonyjohnsonga/msp-beacon:latest
    container_name: msp-beacon
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./config:/data/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
